AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Timeout: 60
    Runtime: nodejs20.x
    MemorySize: 1024
Resources:
  RSSReader:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/RSSReader.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                - !GetAtt Table.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Enabled: true
  ScheduleTweet:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/ScheduleTweet.handler
      Environment:
        Variables:
          TWEET_FUNCTION_ARN: !GetAtt TweetFunction.Arn
          TWEET_FUNCTION_ROLE_ARN: !GetAtt ScheulderRole.Arn
      Events:
        DynamoDBTrigger:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
            MaximumRetryAttempts: 1
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'scheduler:CreateSchedule'
              Resource:
                - '*'
        - Version: 2012-10-17
          Statement:
            - Sid: Statement2
              Effect: Allow
              Action:
                - 'iam:PassRole'
              Resource:
                - !GetAtt ScheulderRole.Arn
  TweetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/TweetFunction.handler
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'ssm:GetParameter'
              Resource:
                - !Sub >-
                  arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/news-comics/*
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  ScheulderRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - scheduler.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-scheduler-policy'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource:
                  - !GetAtt TweetFunction.Arn
