AWSTemplateFormatVersion: 2010-09-09
Transform:
  - 'AWS::Serverless-2016-10-31'
Globals:
  Function:
    Timeout: 60
    MemorySize: 1024
Resources:
  RSSReader:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/RSSReader.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          TABLE_NAME: !Ref Table
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'dynamodb:PutItem'
              Resource:
                - !GetAtt Table.Arn
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)
            Enabled: true
  Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  TweetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: .
      Handler: src/TweetFunction.handler
      Runtime: nodejs18.x
      Events:
        DynamoDBTrigger:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            BatchSize: 1
            StartingPosition: LATEST
            MaximumRetryAttempts: 1
      Policies:
        - Version: 2012-10-17
          Statement:
            - Sid: Statement1
              Effect: Allow
              Action:
                - 'ssm:GetParameter'
              Resource:
                - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/news-comics/*'
